# Dependencies
pygments:         true

# Permalinks
permalink:        pretty

# Setup
tagline:          Algorithms for reproducible bioinformatics
title:            The Köster lab
description:      ''
url:              https://koesterlab.github.io

author:
  name:           'Johannes Köster'
  url:            https://koesterlab.github.io

